include: package:flutter_lints/flutter.yaml
linter:
  rules:
    # intentionally disabled
    prefer_double_quotes: false
    prefer_single_quotes: false
    unnecessary_brace_in_string_interps: false

    constant_identifier_names: false
    non_constant_identifier_names: false
    void_checks: false
    no_logic_in_create_state: false
    unnecessary_overrides: false

    use_key_in_widget_constructors: false

    no_leading_underscores_for_local_identifiers: false
    use_build_context_synchronously: false
    library_private_types_in_public_api: false
    prefer_interpolation_to_compose_strings: false
    depend_on_referenced_packages: false
    file_names: false

analyzer:
  errors:
    # critical errors
    missing_required_param: error
    missing_return: error
    unawaited_futures: error
    always_declare_return_types: error
    prefer_final_fields: error
    annotate_overrides: error

    # warnings
    omit_local_variable_types: warning
    prefer_collection_literals: warning
    unused_import: warning
    unnecessary_this: warning
    prefer_if_null_operators: warning
    prefer_generic_function_type_aliases: warning
    use_function_type_syntax_for_parameters: warning
    prefer_conditional_assignment: warning

    # intentionally disabled
    todo: ignore
    fixme: ignore
    hack: ignore
    unused_element: ignore

    # TODO: these are non-trivial to fix
    deprecated_member_use: ignore

    # TODO: maybe enable. Lots of changes
    avoid_unnecessary_containers: ignore

  # strong-mode:
  #   implicit-casts: true
  #   implicit-dynamic: true
  exclude:
    - test_driver/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.*config.dart
    - lib/**/intl_messages_*.dart
    - lib/generated_plugin_registrant.dart
    - packages/extended_switch/**
    - test/**/*.mocks.dart
 