name: found_space_flutter_web_application
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.0.0
  rxdart: ^0.27.3
  http: ^0.13.1
  provider: ^6.0.0
  mobx: ^2.0.5
  flutter_mobx: ^2.0.6+1
  jiffy: ^5.0.0
  intl: ^0.17.0
  page_transition: ^2.0.5
  json_annotation:
  get_it: ^7.2.0
  cached_network_image: ^3.2.0
  syncfusion_flutter_gauges: ^20.1.61
  flutter_switch: ^0.3.2
  flutter_staggered_grid_view: ^0.6.1
  pretty_qr_code: ^2.0.2
  webfeed: ^0.7.0
  scroll_to_index: ^3.0.1
  expandable_text: ^2.3.0
  flutter_svg: ^1.0.0
  timezone: ^0.9.2
  lottie: ^2.5.0
  fluttertoast: ^8.2.2
  tuple: ^2.0.2
  crypto: ^3.0.3
  mockito: ^5.4.2
  found_space_flutter_rest_api:
    git:
      url: git@github.com:paranjay-patel/PAL-REST-APIs.git
      ref: vishal_automation_experiment

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.1
  r_flutter: #^0.9.0
    git: # using a version from git to get the unreleased `add_file_path_comments` feature. Remove when Version 0.9.1 or later is officially released
      url: git@github.com:timfreiheit/r_flutter.git
      ref: 1a5f986d87b8cd6b8a77b470f69a9ae1d5a2ec60
  freezed: ^2.0.3+1
  mobx_codegen:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/svg/
    - assets/json/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 800

r_flutter:
  add_file_path_comments: false
  asset_classes:
    ".svg":
      import: common/svg_asset_image.dart
      class: SvgAssetImage
