
name: Static Code Analysis

on:
  # push:
  #   branches:
  #     - reply-notification
  pull_request:
    branches:
      - master
      - release*
      - develop
      - main
      - feature

jobs:

  notify-on-starting:
    runs-on: ubuntu-latest
    # env:
    #   SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   
    steps:
    - id: deployment_message
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: "C07C0LDFMK6"
        payload: |
          {
            "text": "Deployment started (In Progress)"
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    - uses: slackapi/slack-github-action@v1.26.0
      with:
        # Unlike the step posting a new message, this step does not accept a channel name.
        # Please use a channel ID, not a name here.
        channel-id: "C07C0LDFMK6"
        payload: |
          {
            "thread_ts": "${{ steps.deployment_message.outputs.ts }}",
            "text": "Deployment finished (Completed)"
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
