name: Pull Request

on:
  # push:
  #   branches:
  #     - reply-notification
  pull_request:
    branches:
      - master
      - release*
      - develop
      - main
      - feature

jobs:
  integration_test:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   
    steps:
      - name: Checkout code
        id: Checkout_code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      
      - name: Setup SSH
        id: Setup-SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Flutter
        id: Setup_flutter
        uses: subosito/flutter-action@v2  
        with:
          flutter-version: '3.22.0'

      - name: Install dependencies
        id: Install_dependencies
        run: flutter pub get

      - name: Flutter Enable Web
        id: flutter-enable-web
        run: flutter config --enable-web

      - name: Install Google Chrome
        id: install-chrome
        run: |
          wget -q https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.72/linux64/chrome-linux64.zip
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "google-chrome --version"
          google-chrome --version 

      - name: Install Chromedriver
        id: Install_Chromedriver
        run: |
          echo "################################################   1  ######################################################"
          wget --quiet https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.72/linux64/chromedriver-linux64.zip
          echo "################################################   2  ######################################################"
          unzip chromedriver-linux64.zip
          echo "################################################   3  ######################################################"
          chmod +x chromedriver
          echo "################################################   4  ######################################################"
          sudo mv chromedriver /usr/bin/
          echo "################################################   5  ######################################################"
          chromedriver --version
          echo "################################################   6  ######################################################"
          chromedriver --port=4444 &

      - name: Integration Test
        id: integration-test
        run: |
          flutter drive --driver=test_driver/integration_test.dart --target=test/sauna_session_test.dart --flavor=red --dart-define=flavor=red -d web-server --release --browser-name=chrome
          
###################################################################################################################

      # - name: Install Chrome
      #   id: install-chrome
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y chromium-browser

      # - name: Start ChromeDriver
      #   id: start-chromedriver
      #   run: |
      #     wget -q -N https://chromedriver.storage.googleapis.com/$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
      #     unzip chromedriver_linux64.zip
      #     sudo mv chromedriver /usr/local/bin/
      #     chromedriver --port=4444 &

      # - name: Integration Test
      #   id: integration-test
      #   run: |
      #     flutter drive --driver=test_driver/integration_test.dart --target=test/sauna_session_test.dart --flavor=red --dart-define=flavor=red -d web-server --release --browser-name=chromium




################################################################################################################


      # - name: Install Chromedriver
      #   id: Install_Chromedriver
      #   run: |
      #     echo "################################################   1  ######################################################"
      #     wget --quiet https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
      #     echo "################################################   2  ######################################################"
      #     unzip chromedriver_linux64.zip
      #     echo "################################################   3  ######################################################"
      #     chmod +x chromedriver
      #     echo "################################################   4  ######################################################"
      #     sudo mv chromedriver /usr/bin/
      #     echo "################################################   5  ######################################################"
      #     chromedriver --version
      #     echo "################################################   6  ######################################################"
      #     chromedriver --port=4444 &
          
      # - name: Run Integration Test
      #   id: Run_Integration_test
      #   run: |
      #     flutter drive --driver=test_driver/integration_test.dart --target=test/sauna_session_test.dart  --flavor=red --dart-define=flavor=red -d web-server
