
name: Pull Request

on:
  # push:
  #   branches:
  #     - reply-notification
  pull_request:
    branches:
      - master
      - release*
      - develop
      - main
      - feature

jobs:
  Code-Analysis:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   
    steps:
      - name: Notify Workflow Starting
        id: Workflow_starting
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "attachments": [
                {
                  "pretext": "*A new PR workflow has started!* :star:",
                  "color": "#0073e6",
                  "fields": [
                    {
                      "title": "Pull Request",
                      "value": "<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>",
                      "short": false
                    },

                    {
                      "title": "Source Branch",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.event.pull_request.head.ref }}|${{ github.event.pull_request.head.ref }}>",
                      "short": true
                    },
                    {
                      "title": "Author",
                      "value": "<https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>",
                      "short": true
                    },
                    {
                      "title": "Target Branch",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.event.pull_request.base.ref }}|${{ github.event.pull_request.base.ref }}>",
                      "short": true
                    },
                    {
                      "title": "Workflow",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "In Progress",
                      "short": true
                    }
                  ]               
                }
              ]
            }

      - name: Checkout code
        id: Checkout_code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      
      # - name: Setup SSH
      #   id: Setup-SSH
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts

      # - name: Set up Flutter
      #   id: Setup_flutter
      #   uses: subosito/flutter-action@v2  
      #   with:
      #     flutter-version: '3.22.0'

      # - name: Install dependencies
      #   id: Install_dependencies
      #   run: flutter pub get

      - name: Run linter
        id: Run_linter
        run: |
          flutter analyze
  
      - name: Notify linter success
        if: success()
        id: Linter_successful_notify
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "thread_ts": "${{ steps.Workflow_starting.outputs.ts }}",
              "attachments": [
                {
                  "color": "00ff00",
                  "fields": [
                    {
                      "title": "Linting",
                      "short": true,
                      "value": "Successful"
                    }
                  ]
                }
              ]
            }
      

      - name: Notify linter failure
        if: failure()
        id: Linter_failed_notify
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "thread_ts": "${{ steps.Workflow_starting.outputs.ts }}",
              "attachments": [
                {
                  "pretext": " ",
                  "color": "FF1A1A",
                  "fields": [
                    {
                      "title": "Linting",
                      "short": true,
                      "value": "Failed"
                    }
                  ]
                }
              ]
            }
      

      # - name: Sonar scanner
      #   id: Sonar_scan
      #   env:
      #     SONAR_SCANNER_VER: sonar-scanner-cli-4.7.0.2747-linux
      #     SONAR_SCANNER_PATH: sonar-scanner-4.7.0.2747-linux/bin
      #   run: |
      #     wget --quiet https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      #     unzip -q sonar-scanner-cli-4.7.0.2747-linux.zip
      #     $SONAR_SCANNER_PATH/sonar-scanner -v
      #     $SONAR_SCANNER_PATH/sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}

      # - name: Quality gate check
      #   id: Quality_gate_check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # - uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     channel-id: "C07B6R6NYUW"
      #     payload: |
      #       {
      #         "thread_ts": "${{ steps.deployment_message.outputs.ts }}",
      #         "text": "workflow Successfull"
      #       }

      # - uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     channel-id: "C07B6R6NYUW"
      #     payload: |
      #       {
      #         "thread_ts": "${{ steps.deployment_message.outputs.ts }}",
      #         "text": "Deployment finished second (Completed)"
      #       }
