
name: Pull Request

on:
  # push:
  #   branches:
  #     - reply-notification
  pull_request:
    branches:
      - master
      - release*
      - develop
      - main
      - feature

jobs:
  Code-Analysis:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   
    steps:
      - id: deployment_message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "text": "PR Workflow Started (In Progress)",
              "attachments": [
                {
                  "pretext": "A new PR workflow has started! :start:",
                  "color": "#0073e6",
                  "fields": [
                    {
                      "title": "Pull Request",
                      "value": "<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>",
                      "short": false
                    },
                    {
                      "title": "Author",
                      "value": "<https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>",
                      "short": true
                    },
                    {
                      "title": "Source Branch",
                      "value": "${{ github.event.pull_request.head.ref }}",
                      "short": true
                    },
                    {
                      "title": "Target Branch",
                      "value": "${{ github.event.pull_request.base.ref }}",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "In Progress",
                      "short": true
                    }
                  ],
                  "actions": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github: View PR"
                      },
                      "url": "${{ github.event.pull_request.html_url }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github: View Action"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }

      - name: Checkout code
        id: Checkout-code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      # env:
      #   SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "thread_ts": "${{ steps.deployment_message.outputs.ts }}",
              "text": "Deployment finished (Completed)"
            }
      # env:
      #   SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "thread_ts": "${{ steps.deployment_message.outputs.ts }}",
              "text": "Deployment finished second (Completed)"
            }
