name: Pull Request

on:
  pull_request:
    branches:
      - master
      - release*
      - develop
      - main
      - feature

jobs:
  Pull_Request:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   
    outputs:
      slack_thread_ts: ${{ steps.Notify_workflow_starting.outputs.ts }}
    steps:
      - name: Notify Workflow Starting
        id: Notify_workflow_starting
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "attachments": [
                {
                  "pretext": "A new *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Pull Request>* workflow has been initiated by *<https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>* for *<https://github.com/${{ github.repository }}|${{ github.repository }}>* 🚀 ",
                  "color": "#0073e6",
                  "fields": [
                    {
                      "title": "Status",
                      "value": "In Progress",
                      "short": true
                    },
                    {
                      "title": "Pull Request",
                      "value": "<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>",
                      "short": true
                    }
                  ]               
                }
              ]
            }

      - name: Checkout code
        id: Checkout_code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
  
      - name: Notify linter success
        if: success()
        id: Notify_linter_success
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "thread_ts": "${{ steps.Notify_workflow_starting.outputs.ts }}",
              "attachments": [
                {
                  "pretext": "PR Workflow Status!",
                  "color": "#1aff1a",
                  "fields": [
                    {
                      "title": "Linting",
                      "value": "Successful",
                      "short": true
                    },
                    {
                      "title": "Workflow",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Pull Request>",
                      "short": true
                    }
                  ]
                }
              ]
            }

      - name: Notify linter failure
        if: failure()
        id: Linter_failed_notify
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "thread_ts": "${{ steps.Notify_workflow_starting.outputs.ts }}",
              "attachments": [
                {
                  "pretext": "PR Workflow Status! :fire_engine:",
                  "color": "#FF1A1A",
                  "fields": [
                    {
                      "title": "Linting",
                      "value": "Failed",
                      "short": true
                    },
                    {
                      "title": "Workflow",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Pull Request>",
                      "short": true
                    }
                  ]
                }
              ]
            }

      - name: Update Workflow Success
        id: Update_workflow_success
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "C07B6R6NYUW"
          update-ts: ${{ steps.Notify_workflow_starting.outputs.ts }}
          payload: |
            {
              "attachments": [
                {
                  "pretext": "A *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Pull Request>* workflow initiated by *<https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>* for *<https://github.com/${{ github.repository }}|${{ github.repository }}>* has completed successfully. ✅",
                  "color": "#1aff1a",
                  "fields": [
                    {
                      "title": "Status",
                      "value": "Successful",
                      "short": true
                    },
                    {
                      "title": "Pull Request",
                      "value": "<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>",
                      "short": true
                    }
                  ]               
                }
              ]
            }

      - name: Update Workflow Failure
        id: Update_workflow_failure
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "C07B6R6NYUW"
          update-ts: ${{ steps.Notify_workflow_starting.outputs.ts }}
          payload: |
            {
              "attachments": [
                {
                  "pretext": "A *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Pull Request>* workflow initiated by *<https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>* for *<https://github.com/${{ github.repository }}|${{ github.repository }}>* has failed. 🚨",
                  "color": "#FF1A1A",
                  "fields": [
                    {
                      "title": "Status",
                      "value": "Failed",
                      "short": true
                    },
                    {
                      "title": "Pull Request",
                      "value": "<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>",
                      "short": true
                    }
                  ]               
                }
              ]
            }

  integration_test:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   
    needs: Pull_Request
    steps:
      - name: Checkout code
        id: Checkout_code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Notify Integration Test Success
        if: success()
        id: Notify_Integration_Test_Success
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "thread_ts": "${{ needs.Pull_Request.outputs.slack_thread_ts }}",
              "attachments": [
                {
                  "pretext": "PR Workflow Status!",
                  "color": "#1aff1a",
                  "fields": [
                    {
                      "title": "Integration Test",
                      "value": "Successful",
                      "short": true
                    },
                    {
                      "title": "Workflow",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Pull Request>",
                      "short": true
                    }
                  ]
                }
              ]
            }

      - name: Notify Integration Test Failure
        if: failure()
        id: Notify_Integration_Test_Failure
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "thread_ts": "${{ needs.Pull_Request.outputs.slack_thread_ts }}",
              "attachments": [
                {
                  "pretext": "PR Workflow Status!",
                  "color": "#FF1A1A",
                  "fields": [
                    {
                      "title": "Integration Test",
                      "value": "Failure",
                      "short": true
                    },
                    {
                      "title": "Workflow",
                      "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Pull Request>",
                      "short": true
                    }
                  ]
                }
              ]
            }
