name: Pull Request

on:
  pull_request: 
    branches:
      - master
      - release**
      - develop
      - main

jobs:
  static-code-analysis:
    runs-on: macos-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
    steps:    
      - name: Checkout code
        id: Checkout-code
        uses: actions/checkout@v3

      - name: Notify Slack
        uses: act10ns/slack@v2
        with:
          channel: 's1-panel'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()

  integration-test:
    if: ${{ (github.event_name == 'pull_request' && (startsWith(github.base_ref, 'release/') || github.base_ref == 'master' || github.base_ref == 'develop' || github.base_ref == 'main')) }}
    runs-on: macos-latest
    permissions: write-all
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout code
        id: Checkout-code
        uses: actions/checkout@v3

      - name: Notify Slack 
        uses: act10ns/slack@v2
        with:
          channel: 's1-panel'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
