
name: Static Code Analysis

on:
  pull_request:
    branches:
      - master
      - release*
      - develop
      - main

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: '19.0.1'

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.22.2' 

    - name: Install dependencies
      run: |
        flutter --version
        dart --version
        flutter pub get

    - name: Run linter
      run: |
        flutter analyze
          
  notify-on-success:
    runs-on: ubuntu-latest
    needs: static-code-analysis
    if: success()
    
    steps:
    - name: notify slack
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        channel-id: 'C07B6R6NYUW'
        payload: |
          {
            "text": "GitHub Action Successfull",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Static code analysis check successful...✅*\n\n*Pull Request:* ${{ github.event.pull_request.title }}\n*Source Branch:* ${{ github.event.pull_request.head.ref }}\n*Target Branch:* ${{ github.event.pull_request.base.ref }}\n*Committer:* ${{ github.actor }}"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":github: View Action"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":git: View Pull Request"
                    },
                    "url": "${{ github.event.pull_request.html_url }}"
                  }
                ]
              }
            ]
          }
        
  notify-on-failure:
    runs-on: ubuntu-latest
    needs: static-code-analysis
    if: failure()
    
    steps:
    - name: notify slack
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        channel-id: 'C07B6R6NYUW'
        payload: |
          {
            "text": "GitHub Action Failed",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Static code analysis check failed...⚠️ :fire_engine:*\n\n*Pull Request:* ${{ github.event.pull_request.title }}\n*Source Branch:* ${{ github.event.pull_request.head.ref }}\n*Target Branch:* ${{ github.event.pull_request.base.ref }}\n*Committer:* ${{ github.actor }}"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":github: View Action"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":git: View Pull Request"
                    },
                    "url": "${{ github.event.pull_request.html_url }}"
                  }
                ]
              }
            ]
          }
