
name: Static Code Analysis

on:
  # push:
  #   branches:
  #     - reply-notification
  pull_request:
    branches:
      - master
      - release*
      - develop
      - main
      - feature

jobs:

  notify-on-starting:
    runs-on: ubuntu-latest
    steps:
    - name: notify-on-starting
      id: notify-on-starting
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        channel-id: 'C07B6R6NYUW'
        payload: |
          {
            "attachments": [
              {
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Pull Request Wrokflow Started",
                    "short": true,
                    "value": "In Progress"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "\n\n*Pull Request:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n*Source Branch:* <${{ github.server_url }}/${{ github.repository }}/tree/${{ github.event.pull_request.head.ref }}|${{ github.event.pull_request.head.ref }}>\n*Target Branch:* <${{ github.server_url }}/${{ github.repository }}/tree/${{ github.event.pull_request.base.ref }}|${{ github.event.pull_request.base.ref }}>\n*Committer:* <${{ github.event.pull_request.user.html_url }}|${{ github.event.pull_request.user.login }}>"
                }
              }
            ]
          }

  static-code-analysis:
    runs-on: ubuntu-latest
    needs: notify-on-starting
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    # - name: Install Java
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: '19.0.1'

    # - name: Set up Flutter
    #   uses: subosito/flutter-action@v1
    #   with:
    #     flutter-version: '3.22.2' 

    # - name: Install dependencies
    #   run: |
    #     flutter --version
    #     dart --version
    #     flutter pub get

    # - name: Run linter
    #   run: |
    #     flutter analyze
          
  notify-on-success:
    runs-on: ubuntu-latest
    needs: static-code-analysis
    if: success()
    
    steps:
    - name: notify slack
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      # env:
      #   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        channel-id: 'C07B6R6NYUW'
        payload: |
          {
            "text": "GitHub Action Successfull",
            "blocks": [
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":github: View Action"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":git: View Pull Request"
                    },
                    "url": "${{ github.event.pull_request.html_url }}"
                  }
                ]
              }
            ]
          }
        
  notify-on-failure:
    runs-on: ubuntu-latest
    needs: static-code-analysis
    if: failure()
    
    steps:
    - name: notify slack
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      # env:
      #   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        channel-id: 'C07B6R6NYUW'
        payload: |
          {
            "text": "GitHub Action Failed",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Static code analysis check failed...⚠️ :fire_engine:*\n\n*Pull Request:* ${{ github.event.pull_request.title }}\n*Source Branch:* ${{ github.event.pull_request.head.ref }}\n*Target Branch:* ${{ github.event.pull_request.base.ref }}\n*Auther :* ${{ github.actor }}"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":github: View Action"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": ":git: View Pull Request"
                    },
                    "url": "${{ github.event.pull_request.html_url }}"
                  }
                ]
              }
            ]
          }
