name: Pull Request

on:
  push:
    branches:
      - reply-notification
  pull_request:
    branches:
      - master
      - release/**
      - develop
      - main

jobs:
  static-code-analysis:
    runs-on: macos-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
    steps:
      - name: Checkout code
        id: Checkout-code
        uses: actions/checkout@v3

      - name: Send initial Slack notification
        id: notify-slack-start
        run: |
          ./notify_slack.sh $SLACK_WEBHOOK_URL android-app "starting" "Static Code Analysis started"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send final Slack notification
        run: |
          ./notify_slack.sh $SLACK_WEBHOOK_URL android-app "${{ job.status }}" "Static Code Analysis completed" ${{ steps.notify-slack-start.outputs.ts }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  integration-test:
    if: ${{ github.event_name == 'pull_request' && (github.base_ref == 'master' || github.base_ref == 'main' || github.base_ref == 'develop' || startsWith(github.base_ref, 'release')) }}
    runs-on: macos-latest
    permissions: write-all
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout code
        id: Checkout-code
        uses: actions/checkout@v3

      - name: Send initial Slack notification
        id: notify-slack-start
        run: |
          ./notify_slack.sh $SLACK_WEBHOOK_URL android-app "starting" "Integration Test started"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send final Slack notification
        run: |
          ./notify_slack.sh $SLACK_WEBHOOK_URL android-app "${{ job.status }}" "Integration Test completed" ${{ steps.notify-slack-start.outputs.ts }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
