name: Pull Request

on:
  push:
    branches:
      - reply-notification-artifact
  pull_request:
    branches:
      - master
      - release/**
      - develop
      - main
      - feature

jobs:
  Notify_Slack:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   
    outputs:
      slack_initial_thread_ts: ${{ steps.Notify_workflow_starting.outputs.ts }}  
    steps:
      - name: Notify Workflow Starting
        id: Notify_Workflow_Starting
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "attachments": [
                {
                  "pretext": "A new *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Pull Request>* workflow has been initiated by *<https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>* for *<https://github.com/${{ github.repository }}|${{ github.repository }}>* 🚀 ",
                  "color": "#0073e6",
                  "fields": [
                    {
                      "title": "Status",
                      "value": "In Progress",
                      "short": true
                    },
                    {
                      "title": "Pull Request",
                      "value": "<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>",
                      "short": true
                    }
                  ]               
                }
              ]
            }
            
  store-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Capture Pull Request Information
        run: |
          echo "PR_TITLE=${{ github.event.pull_request.title }}" > pr_info.txt
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> pr_info.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr-info
          path: pr_info.txt
          
