
name: Pull Request

on:
  # push:
  #   branches:
  #     - reply-notification
  pull_request:
    branches:
      - master
      - release*
      - develop
      - main
      - feature

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   
    steps:
      - id: deployment_message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "text": "Deployment started (In Progress)"
            }

      - name: Checkout code
        id: Checkout-code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      # env:
      #   SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "thread_ts": "${{ steps.deployment_message.outputs.ts }}",
              "text": "Deployment finished (Completed)"
            }
      # env:
      #   SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C07B6R6NYUW"
          payload: |
            {
              "thread_ts": "${{ steps.deployment_message.outputs.ts }}",
              "text": "Deployment finished second (Completed)"
            }
