name: Pull Request

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
      - release*
      - develop 
      - main
  workflow_dispatch:

jobs:
  static-code-analysis:
    if: ${{ github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'master' || startsWith(github.base_ref, 'release/') || github.base_ref == 'develop') }}
    runs-on: macos-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notify Slack
        uses: act10ns/slack@v2
        with:
          channel: 's1-panel'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()

  integration-test:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'master' || github.base_ref == 'develop')) }}
    runs-on: macos-latest
    permissions: write-all
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notify Slack 
        uses: act10ns/slack@v2
        with:
          channel: 's1-panel'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
