
name: Static Code Analysis

on:
  # push:
  #   branches:
  #     - reply-notification
  pull_request:
    branches:
      - master
      - release*
      - develop
      - main
      - feature

jobs:

  notify-on-starting:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   
    steps:
    - name: notify-on-starting
      id: notify-on-starting
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: "C07B6R6NYUW"
        payload: |
          {
            "text": "Deployment started (In Progress)"
          }

    - name: notify-on-complete
      id: notify-on-complete
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # Unlike the step posting a new message, this step does not accept a channel name.
        # Please use a channel ID, not a name here.
        channel-id: "C07B6R6NYUW"
        payload: |
          {
            "thread_ts": "${{ steps.deployment_message.outputs.ts }}",
            "text": "Deployment finished (Completed)"
          }
        
