name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}  
    steps:
      - name: Checkout Code
        id: Checkout_Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Setup SSH
        id: Setup_SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run validation script
        run: |
          chmod +x ./validator_script.sh
          ./validator_script.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Failure
        if: failure()
        id: Notify_Failure
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "C07B6R6NYUW"
          slack-message:  "A *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|PR Validation>* workflow initiated by *<https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>* on pull request *<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>* for *<https://github.com/${{ github.repository }}|${{ github.repository }}>* has failed!.🚨"
