name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}  
    steps:
      - name: Checkout Code
        id: Checkout_Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Setup SSH
        id: Setup_SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get PR details
        id: pr_details
        run: |
          echo "PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "PR_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "PR_DESCRIPTION=$(jq --raw-output .pull_request.body "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "REPO_FULL_NAME=$(jq --raw-output .repository.full_name "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV

      - name: Log PR details
        run: |
          echo "PR Number: $PR_NUMBER"
          echo "PR Title: $PR_TITLE"
          echo "Repository: $REPO_FULL_NAME"
          echo "PR Description: $PR_DESCRIPTION"

      # - name: Run validation script
      #   run: |
      #     git clone git@github.com:Healtech-Pty-Ltd/DevOps.git
      #     cd DevOps/pr-validation-script
      #     chmod +x ./pr_validation.sh
      #     ./pr_validation.sh
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Check JIRA Ticket Reference
        run: .github/scripts/check_jira_ticket.sh "$PR_TITLE"

      - name: Check Commits Signed
        run: .github/scripts/check_commits_signed.sh "$PR_NUMBER" "$REPO_FULL_NAME"

      - name: Check PR Description
        run: .github/scripts/check_pr_description.sh "$PR_DESCRIPTION" "$jira_ticket"
        env:
          # jira_ticket: $(echo "$PR_TITLE" | awk '{print toupper($0)}' | cut -d: -f1)
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Notify Failure
        if: failure()
        id: Notify_Failure
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "C07B6R6NYUW"
          # slack-message: |
          #   A `<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|PR Validation>` workflow initiated by `<https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>` on pull request `<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>` for `<https://github.com/${{ github.repository }}|${{ github.repository }}>` has *FAILED!* 🚨
          # # slack-message: |
          # #   A *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|PR Validation>* workflow initiated by *<https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}>* on pull request `<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>` for *<https://github.com/${{ github.repository }}|${{ github.repository }}>* has *FAILED!* 🚨
 
          payload: |
           {
             "text": "PR validation workflow failed 🚨",
             "blocks": [
               {
                 "type": "section",
                 "text": {
                   "type": "mrkdwn",
                   "text": "A <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|PR Validation> workflow initiated by <https://github.com/${{ github.event.pull_request.user.login }}|${{ github.event.pull_request.user.login }}> on pull request <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}> for <https://github.com/${{ github.repository }}|${{ github.repository }}> has *FAILED!* 🚨"
                 }
               },
               {
                 "type": "actions",
                 "elements": [
                   {
                     "type": "button",
                     "text": {
                       "type": "plain_text",
                       "text": ":github: View workflow"
                     },
                     "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                   }
                 ]
               }
             ]
           }
