name: Validate PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run validation script
        run: |
          chmod +x ./validator_script.sh
          ./validator_script.sh
        # env:
        #   GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
